// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: kmm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DaemonConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modules []*DaemonConfigResponse_Module `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
}

func (x *DaemonConfigResponse) Reset() {
	*x = DaemonConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kmm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonConfigResponse) ProtoMessage() {}

func (x *DaemonConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kmm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonConfigResponse.ProtoReflect.Descriptor instead.
func (*DaemonConfigResponse) Descriptor() ([]byte, []int) {
	return file_kmm_proto_rawDescGZIP(), []int{0}
}

func (x *DaemonConfigResponse) GetModules() []*DaemonConfigResponse_Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

type DaemonConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KernelVersion string `protobuf:"bytes,1,opt,name=kernelVersion,proto3" json:"kernelVersion,omitempty"`
	HostName      string `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
}

func (x *DaemonConfigRequest) Reset() {
	*x = DaemonConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kmm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonConfigRequest) ProtoMessage() {}

func (x *DaemonConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kmm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonConfigRequest.ProtoReflect.Descriptor instead.
func (*DaemonConfigRequest) Descriptor() ([]byte, []int) {
	return file_kmm_proto_rawDescGZIP(), []int{1}
}

func (x *DaemonConfigRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *DaemonConfigRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

type DaemonConfigResponse_Module struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleName          string   `protobuf:"bytes,1,opt,name=moduleName,proto3" json:"moduleName,omitempty"`
	ImageName           string   `protobuf:"bytes,2,opt,name=imageName,proto3" json:"imageName,omitempty"`
	PullSecret          *string  `protobuf:"bytes,3,opt,name=pullSecret,proto3,oneof" json:"pullSecret,omitempty"`
	ModulesLoadingOrder []string `protobuf:"bytes,4,rep,name=modulesLoadingOrder,proto3" json:"modulesLoadingOrder,omitempty"`
	FirmwarePath        *string  `protobuf:"bytes,5,opt,name=firmwarePath,proto3,oneof" json:"firmwarePath,omitempty"`
	DirName             *string  `protobuf:"bytes,6,opt,name=dirName,proto3,oneof" json:"dirName,omitempty"`
}

func (x *DaemonConfigResponse_Module) Reset() {
	*x = DaemonConfigResponse_Module{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kmm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonConfigResponse_Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonConfigResponse_Module) ProtoMessage() {}

func (x *DaemonConfigResponse_Module) ProtoReflect() protoreflect.Message {
	mi := &file_kmm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonConfigResponse_Module.ProtoReflect.Descriptor instead.
func (*DaemonConfigResponse_Module) Descriptor() ([]byte, []int) {
	return file_kmm_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DaemonConfigResponse_Module) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *DaemonConfigResponse_Module) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *DaemonConfigResponse_Module) GetPullSecret() string {
	if x != nil && x.PullSecret != nil {
		return *x.PullSecret
	}
	return ""
}

func (x *DaemonConfigResponse_Module) GetModulesLoadingOrder() []string {
	if x != nil {
		return x.ModulesLoadingOrder
	}
	return nil
}

func (x *DaemonConfigResponse_Module) GetFirmwarePath() string {
	if x != nil && x.FirmwarePath != nil {
		return *x.FirmwarePath
	}
	return ""
}

func (x *DaemonConfigResponse_Module) GetDirName() string {
	if x != nil && x.DirName != nil {
		return *x.DirName
	}
	return ""
}

var File_kmm_proto protoreflect.FileDescriptor

var file_kmm_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6b, 0x6d, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe2, 0x02, 0x0a, 0x14,
	0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x1a, 0x91, 0x02, 0x0a,
	0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0a, 0x70, 0x75, 0x6c, 0x6c, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x75, 0x6c,
	0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x13, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x73, 0x4c, 0x6f, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73,
	0x4c, 0x6f, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0c,
	0x66, 0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x0c, 0x66, 0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x64, 0x69, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x07, 0x64, 0x69, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x70, 0x75, 0x6c, 0x6c, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x66, 0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x64, 0x69, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x57, 0x0a, 0x13, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x6b, 0x65, 0x72, 0x6e, 0x65,
	0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x47, 0x0a, 0x03, 0x4b, 0x4d, 0x4d,
	0x12, 0x40, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x14, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x44, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x2d, 0x73, 0x69, 0x67, 0x73,
	0x2f, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2d, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kmm_proto_rawDescOnce sync.Once
	file_kmm_proto_rawDescData = file_kmm_proto_rawDesc
)

func file_kmm_proto_rawDescGZIP() []byte {
	file_kmm_proto_rawDescOnce.Do(func() {
		file_kmm_proto_rawDescData = protoimpl.X.CompressGZIP(file_kmm_proto_rawDescData)
	})
	return file_kmm_proto_rawDescData
}

var file_kmm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kmm_proto_goTypes = []interface{}{
	(*DaemonConfigResponse)(nil),        // 0: DaemonConfigResponse
	(*DaemonConfigRequest)(nil),         // 1: DaemonConfigRequest
	(*DaemonConfigResponse_Module)(nil), // 2: DaemonConfigResponse.Module
}
var file_kmm_proto_depIdxs = []int32{
	2, // 0: DaemonConfigResponse.modules:type_name -> DaemonConfigResponse.Module
	1, // 1: KMM.GetDaemonConfig:input_type -> DaemonConfigRequest
	0, // 2: KMM.GetDaemonConfig:output_type -> DaemonConfigResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kmm_proto_init() }
func file_kmm_proto_init() {
	if File_kmm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kmm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kmm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kmm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonConfigResponse_Module); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kmm_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kmm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kmm_proto_goTypes,
		DependencyIndexes: file_kmm_proto_depIdxs,
		MessageInfos:      file_kmm_proto_msgTypes,
	}.Build()
	File_kmm_proto = out.File
	file_kmm_proto_rawDesc = nil
	file_kmm_proto_goTypes = nil
	file_kmm_proto_depIdxs = nil
}
