// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: kmm.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KMMClient is the client API for KMM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KMMClient interface {
	GetDaemonConfig(ctx context.Context, in *DaemonConfigRequest, opts ...grpc.CallOption) (*DaemonConfigResponse, error)
}

type kMMClient struct {
	cc grpc.ClientConnInterface
}

func NewKMMClient(cc grpc.ClientConnInterface) KMMClient {
	return &kMMClient{cc}
}

func (c *kMMClient) GetDaemonConfig(ctx context.Context, in *DaemonConfigRequest, opts ...grpc.CallOption) (*DaemonConfigResponse, error) {
	out := new(DaemonConfigResponse)
	err := c.cc.Invoke(ctx, "/KMM/GetDaemonConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KMMServer is the server API for KMM service.
// All implementations must embed UnimplementedKMMServer
// for forward compatibility
type KMMServer interface {
	GetDaemonConfig(context.Context, *DaemonConfigRequest) (*DaemonConfigResponse, error)
	mustEmbedUnimplementedKMMServer()
}

// UnimplementedKMMServer must be embedded to have forward compatible implementations.
type UnimplementedKMMServer struct {
}

func (UnimplementedKMMServer) GetDaemonConfig(context.Context, *DaemonConfigRequest) (*DaemonConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDaemonConfig not implemented")
}
func (UnimplementedKMMServer) mustEmbedUnimplementedKMMServer() {}

// UnsafeKMMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KMMServer will
// result in compilation errors.
type UnsafeKMMServer interface {
	mustEmbedUnimplementedKMMServer()
}

func RegisterKMMServer(s grpc.ServiceRegistrar, srv KMMServer) {
	s.RegisterService(&KMM_ServiceDesc, srv)
}

func _KMM_GetDaemonConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMMServer).GetDaemonConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KMM/GetDaemonConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMMServer).GetDaemonConfig(ctx, req.(*DaemonConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KMM_ServiceDesc is the grpc.ServiceDesc for KMM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KMM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "KMM",
	HandlerType: (*KMMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDaemonConfig",
			Handler:    _KMM_GetDaemonConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kmm.proto",
}
