steps:
  - name: gcr.io/cloud-builders/docker
    args:
    - build
    - --build-arg
    - TARGET=manager
    - --tag=gcr.io/$PROJECT_ID/kernel-module-management-operator:$_GIT_TAG
    - --tag=gcr.io/$PROJECT_ID/kernel-module-management-operator:latest
    - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - TARGET=manager-hub
      - --tag=gcr.io/$PROJECT_ID/kernel-module-management-operator-hub:$_GIT_TAG
      - --tag=gcr.io/$PROJECT_ID/kernel-module-management-operator-hub:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - TARGET=manager-spoke
      - --tag=gcr.io/$PROJECT_ID/kernel-module-management-operator-spoke:$_GIT_TAG
      - --tag=gcr.io/$PROJECT_ID/kernel-module-management-operator-spoke:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/$PROJECT_ID/kernel-module-management-signimage:$_GIT_TAG
      - --tag=gcr.io/$PROJECT_ID/kernel-module-management-signimage:latest
      - --file=Dockerfile.signimage
      - .
# this prevents errors if you don't use both _GIT_TAG and _PULL_BASE_REF,
# or any new substitutions added in the future.
options:
  substitution_option: ALLOW_LOOSE
images:
  - gcr.io/$PROJECT_ID/kernel-module-management-operator:$_GIT_TAG
  - gcr.io/$PROJECT_ID/kernel-module-management-operator:latest
  - gcr.io/$PROJECT_ID/kernel-module-management-operator-hub:$_GIT_TAG
  - gcr.io/$PROJECT_ID/kernel-module-management-operator-hub:latest
  - gcr.io/$PROJECT_ID/kernel-module-management-operator-spoke:$_GIT_TAG
  - gcr.io/$PROJECT_ID/kernel-module-management-operator-spoke:latest
  - gcr.io/$PROJECT_ID/kernel-module-management-signimage:$_GIT_TAG
  - gcr.io/$PROJECT_ID/kernel-module-management-signimage:latest
