---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kmm.sigs.k8s.io
  resources:
  - managedclustermodules
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kmm.sigs.k8s.io
  resources:
  - managedclustermodules/finalizers
  verbs:
  - update
- apiGroups:
  - kmm.sigs.k8s.io
  resources:
  - managedclustermodules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
